name: 'Terraform Production'

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Enter 'YES' to confirm:"
        required: true
        default: 'NO'

jobs:
  terraform_dev:
    name: 'Terraform Production'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_WORKSPACE: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      run: echo I am deploying Production!
