name: 'Production'

on:
  push:
    branches:
    - production
  pull_request:
    branches:
    - production
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Enter 'YES' to confirm:"
        required: true
        default: 'YES'



jobs:
  terraform_dev:
    name: 'Terraform Production'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_WORKSPACE: production

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Pull Request
        run: echo Hello, world Production Pull Request ${{ github.event_name }}!

      - name: Push
        if: github.ref == 'refs/heads/production' && github.event_name == 'push'
        run: echo Hello, world Production Push ${{ github.event_name }}!
