name: 'Production'

on:
  push:
    branches:
    - production
  pull_request:
    branches:
    - production

jobs:
  terraform_dev:
    name: 'Terraform Production'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_WORKSPACE: production

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        if: github.ref == 'refs/heads/production'
        run: echo Hello, world Production!
