name: 'Production'

on:
  push:
    branches:
    - production
  pull_request:
    branches:
    - production

jobs:
  terraform_dev:
    name: 'Terraform Production'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_WORKSPACE: production

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Pull Request
        if: github.ref == 'refs/heads/production' && github.event_name == 'pull request'
        run: echo Hello, world Production Pull Request!

      - name: Push
        if: github.ref == 'refs/heads/production' && github.event_name == 'push'
        run: echo Hello, world Production Push!
