name: 'Staging'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  terraform_dev:
    name: 'Terraform Staging'
    runs-on: ubuntu-latest
    environment: staging
    env:
      TF_WORKSPACE: staging

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: gh auth login --hostname GitHub.com --with-token < token.txt
        run: gh auth status
