name: 'Terraform Staging'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  terraform_dev:
    name: 'Terraform Staging'
    runs-on: ubuntu-latest
    environment: staging
    env:
      TF_WORKSPACE: staging

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      run: echo I am deploying Staging!
