name: 'Staging'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  terraform_dev:
    name: 'Terraform Staging'
    runs-on: ubuntu-latest
    environment: staging
    env:
      TF_WORKSPACE: staging

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Pull Request
        if: github.event_name == 'pull_request'
        run: echo Hello, world Staging Pull Request!

      - name: Push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          TOKEN=${{ secrets.GITHUB_TOKEN }}
          bash ./create-pull-request.sh $TOKEN
